### ISSUE TITLE
Redirects/web issues

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/atlas-d2k-www#18]
List of redirects:

| From | To |
|---|---|
| gudmap.org/data/ | atlas-d2k.org/chaise/ |
| gudmap.org/chaise/ | atlas-d2k.org/chaise/ |
| rebuildingakidney.org/data/ | atlas-d2k.org/chaise/ |
| rebuildingakidney.org/chaise/ | atlas-d2k.org/chaise/ |
| Everything else: |  |
| gudmap.org/* | atlas-d2k.org/gudmap/ |
| rebuildingakidney.org/* | atlas-d2k.org/rebuildingakidney/ |

**Comment by crisaless** [comment]
If it's not too late, I'd like to expand the redirects. There are some important old links that may take people a while to decipher once they get to the new landing pages:

| From                                     | To this relative path on atlas-d2k.org |
|------------------------------------------|----------------------------------------|
| /chaise/                                 | /chaise/                               |
| /data/                                   | /chaise/                               |
|                                          |                                        |
| gudmap.org:                              |                                        |
| gudmap.org/about/usage.html              | /gudmap/citing-gudmap/                 |
| gudmap.org/citing-gudmap/                | /gudmap/citing-gudmap/                 |
| gudmap.org/using-gudmap/citing-gudmap/               | /gudmap/citing-gudmap/                 |
| gudmap.org/references/                   | /resources/                            |
| gudmap.org/tutorials/                    | /tutorials/                            |
| gudmap.org/projects/                     | /gudmap/projects/                      |
| gudmap.org/external-resources/           | /tools/                                |
| gudmap.org/Docs/           | /gudmap/Docs/                               |
| gudmap.org/downloads/           | /gudmap/downloads/                               |
| gudmap.org/pdf/           | /gudmap/pdf/                               |
| gudmap.org/using-gudmap/           | https://informatics-isi-edu.github.io/atlas-d2k-docs/docs/home/                            |
| gudmap.org/About/Tutorial/DevMRS.html           | /tutorials/urogenital-dev/reproductive-system/                   |
| gudmap.org/About/Tutorial/DevMUS.html           | /tutorials/urogenital-dev/urinary-system/                  |
| gudmap.org/About/Projects/Gudmap2/Cohn.html           | /gudmap/projects/gudmap2/cohn-group/                 |
| gudmap.org/Organ_Summaries/           | /resources/tissue-summaries/                |
|                                          |                                        |
| rbk:                                     |                                        |
| rebuildingakidney.org/projects/          | /rebuildingakidney/projects/           |
| rebuildingakidney.org/functional-assays/ | /resources/functional-assays/          |
| rebuildingakidney.org/cell-lines/        | /resources/cell-lines/                 |
| rebuildingakidney.org/collaborate.html   | /collaboration/                        |
| rebuildingakidney.org/partnership-project-program.html   | /collaboration/op-pool/                   |
| rebuildingakidney.org/tools/             | /tools/                                |
| rebuildingakidney.org/about/usage.html   | /rebuildingakidney/citing/             |
| rebuildingakidney.org/downloads/   | /rebuildingakidney/downloads/             |
|                                          |                                        |
| Everything else that doesn't fit above:  |                                        |
| gudmap.org/*                             | /gudmap/                               |
| rebuildingakidney.org/*                  | /rebuildingakidney/                    |

**Comment by ljpearlman** [comment]
Done on staging and production. Three things to note:

1. Cached rbk/gudmap pages can make things look broken -- people should clear their caches (really clear them, not just force-reload individual pages).
2. There's no /tools on atlas-d2k, so I made those redirects to /resources/tools instead.
3. There was never /data in gudmap/rbk, so I didn't add a redirect for it.

**Comment by ljpearlman** [comment]
Also did dev.
