### ISSUE TITLE
Navbar not showing on dev.gudmap and other link changes (chaise-config)

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/atlas-d2k-www#26]
Just over a week ago, @crisaless noticed the loaded chaise-config for `dev.rebuildingakidney.org` was not showing the navbar menu options properly after some refactoring. This was because dev rbk was not in the `configRules.hosts` array. This is the same reason that the navbar doesn't show properly on `dev.gudmap.org`. For consistency, it should also be added to `hosts`.

Another issue @hongsudt noticed was that the links in `navbarMenu` of chaise-config still contain `pcid=`. This should be removed from all links in the chaise-config since chaise is attaching a more appropriate `pcid` based on the navbar links being in a static page or a chaise app page.

**Comment by crisaless** [comment]
I updated chaise-config.js on dev.rebuildingakidney.org (using migration-rbk-gudmap branch)

**Comment by crisaless** [comment]
@jrchudy can you please review?

**Comment by jrchudy** [comment]
Sorry I didn't see this notification in github. I tested this on gudmap and it is working as I expect now. It is working on dev.rebuildingakidney.org as well even though the content has changed considerably 😄
