### ISSUE TITLE
Remove `ad` from asset filenames

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/atlas-d2k-www#38]
Hongsuda and I noticed a difference with the displayed content between our screens for the current `dev.rebuildingakidney.org` homepage which is in progress migrating over to atlas-d2k homepage. We were able to determine that the assets added, `rbk-ad-horizontal.png` and `gudmap-ad-horizontal.png`, get blocked by her adblocker when trying to load them. We suspect that using `ad` in the name of assets makes them automatically get blocked and more users might have this issue.

**Comment by crisaless** [comment]
Fixed
