### ISSUE TITLE
Display border and background of markdown tables

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/atlas-d2k-www#58]
By default, chaise will display the border and backgrounds for markdown tables. But [these rules](https://github.com/informatics-isi-edu/atlas-d2k-www/blob/master/assets/css/chaise.css#L216,L234) are removing them on atlas-d2k. I don't think that's intentional. Or at least I don't think this should be applied to all tables. 

We should figure out why these rules are added here and either remove them or make them more specific to where we want to remove the border/background.

Looking at the history of changes, it seems like these rules were introduced by [the initial commit](https://github.com/informatics-isi-edu/atlas-d2k-www/commit/0a4a42466a70443c9c828d7b760f4cb08b70ecdd#diff-8fcea1466c8080a5684f85eeb25f0e5aab46402c69c8fcf477e0f7994d855f19) which most probably was copied from another server (and most probably are not needed by atlas-d2k as the rest of the rules in that commit have already been removed or changed).

**Comment by crisaless** [comment]
The fix has been pushed to production.
